---
# tasks file for revenni.sysdig

- name: install sysdig | repo key
  apt_key:
    url: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
    state: present

- name: install sysdig | sysdig repo
  apt_repository:
    repo: deb https://download.sysdig.com/stable/deb stable-$(ARCH)/
    state: present
    filename: draios

- name: install sysdig | packages
  apt:
    update_cache: yes
    pkg:
    - sysdig
