---
# tasks file for revenni.falco

- name: install falco | repo key
  apt_key:
    url: https://falco.org/repo/falcosecurity-3672BA8F.asc
    state: present

- name: install falco | falco repo
  apt_repository:
    repo: deb https://dl.bintray.com/falcosecurity/deb stable main
    state: present
    filename: falcosecurity

- name: install falco | packages
  apt:
    update_cache: yes
    pkg:
    - falco
    - jq
